.PHONY: clean All

All:
	@echo "----------Building project:[ EncryptDecrypt - Debug ]----------"
	@cd "EncryptDecrypt" && "$(MAKE)" -f  "EncryptDecrypt.mk"
clean:
	@echo "----------Cleaning project:[ EncryptDecrypt - Debug ]----------"
	@cd "EncryptDecrypt" && "$(MAKE)" -f  "EncryptDecrypt.mk" clean
