.PHONY: clean All

All:
	@echo "----------Building project:[ BinarySearch - Debug ]----------"
	@cd "BinarySearch" && "$(MAKE)" -f  "BinarySearch.mk"
clean:
	@echo "----------Cleaning project:[ BinarySearch - Debug ]----------"
	@cd "BinarySearch" && "$(MAKE)" -f  "BinarySearch.mk" clean
