.PHONY: clean All

All:
	@echo "----------Building project:[ sqrt - Debug ]----------"
	@cd "sqrt" && "$(MAKE)" -f  "sqrt.mk"
clean:
	@echo "----------Cleaning project:[ sqrt - Debug ]----------"
	@cd "sqrt" && "$(MAKE)" -f  "sqrt.mk" clean
