.PHONY: clean All

All:
	@echo "----------Building project:[ Horner - Debug ]----------"
	@cd "Horner" && "$(MAKE)" -f  "Horner.mk"
clean:
	@echo "----------Cleaning project:[ Horner - Debug ]----------"
	@cd "Horner" && "$(MAKE)" -f  "Horner.mk" clean
