.PHONY: clean All

All:
	@echo "----------Building project:[ Demo - Debug ]----------"
	@cd "Demo" && "$(MAKE)" -f  "Demo.mk"
clean:
	@echo "----------Cleaning project:[ Demo - Debug ]----------"
	@cd "Demo" && "$(MAKE)" -f  "Demo.mk" clean
